# Name of the GitHub Actions workflow
name: Java CI with Maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Sets up a Java JDK environment for use in actions
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      # Grant execute permission for the mvnw wrapper
      - name: Make gradlew executable
        run: chmod +x ./mvnw

      # Builds the project with the Maven wrapper
      - name: Build with Maven Wrapper
        run: ./mvnw -B package --file pom.xml

      # Optional: Upload artifact for deployment or other jobs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: target/*.jar

